/**
 * GENERATED by scripts/gen-boot-script.ts — do not edit by hand.
 * Cache-busting version for the /dd-boot.js analytics bootstrap asset.
 */
export const BOOT_SCRIPT_SRC = "/dd-boot.js?v=f4e08f87";
