/**
 * Responsive sources for the photography collection.
 *
 * The colored-pencil illustrations have shipped 700w/1400w WebP for a while
 * (see sketch-sources.ts); the photographs did not, so a 1536x1024 JPEG was
 * being downloaded to fill a 384px card. Every photo in src/assets now has
 * crop-normalised WebP variants generated by scripts/gen-photo-variants.py,
 * plus an average tone used as a load-in placeholder.
 *
 * Variants are never upscaled, so the "1400" slot can really be 1024px wide.
 * The manifest records the true width and the srcset descriptor uses it —
 * otherwise the browser would pick a file that cannot deliver the density it
 * was promised.
 */

import manifest from "@/assets/photo-manifest.json";

type PhotoEntry = { tone: string; variants: Record<string, number> };

const MANIFEST = manifest as Record<string, PhotoEntry>;

const webp = import.meta.glob<string>("../assets/*-{700,1400}.webp", {
  eager: true,
  query: "?url",
  import: "default",
});

/** basename ("recipe-confit") -> { "700": url, "1400": url } */
const URLS: Record<string, Record<string, string>> = {};

for (const [path, url] of Object.entries(webp)) {
  const match = /\/([^/]+)-(700|1400)\.webp$/.exec(path);
  if (!match) continue;
  const [, name, slot] = match;
  (URLS[name!] ??= {})[slot!] = url;
}

/** Photo basename from any built asset URL (`recipe-confit-Bk3xQ1.jpg`). */
export function photoNameFromSrc(src: string): string | null {
  const file = src.split(/[?#]/)[0]!.split("/").pop();
  if (!file) return null;
  const base = file.replace(/\.(?:jpg|jpeg|webp|png)$/i, "").replace(/-(?:700|1400)$/, "");

  const known = Object.keys(MANIFEST)
    .filter((name) => base === name || base.startsWith(`${name}-`))
    .sort((a, b) => b.length - a.length)[0];
  return known ?? null;
}

/** srcset for a photo, or null when it has no generated variants. */
export function photoSrcSet(src: string): string | null {
  const name = photoNameFromSrc(src);
  const entry = name ? MANIFEST[name] : undefined;
  const urls = name ? URLS[name] : undefined;
  if (!entry || !urls) return null;
  const parts = Object.entries(entry.variants)
    .filter(([slot]) => urls[slot])
    .map(([slot, realWidth]) => `${urls[slot]} ${realWidth}w`);
  return parts.length > 0 ? parts.join(", ") : null;
}

/**
 * Average tone of a photo, painted behind it while it loads so the grid warms
 * up instead of flashing empty paper. Null for unknown art.
 */
export function photoTone(src: string): string | null {
  const name = photoNameFromSrc(src);
  return (name && MANIFEST[name]?.tone) || null;
}

/** Best single URL for preloading a photo at hero size. */
export function photoPreloadHref(src: string): string {
  const name = photoNameFromSrc(src);
  if (!name) return src;
  return URLS[name]?.["1400"] ?? URLS[name]?.["700"] ?? src;
}

/** `sizes` hints matching where photography actually renders. */
export const PHOTO_SIZES = {
  /** Recipe hero inside the article column (~700px on desktop). */
  hero: "(min-width: 1024px) 700px, 100vw",
  /** Three-up card grid. */
  card: "(min-width: 1024px) 380px, (min-width: 640px) 50vw, 100vw",
  /**
   * Pillar tiles, keyed by how many columns of the three-up grid they occupy.
   * A tile that spans two or three columns needs the large variant; a single
   * column does not.
   */
  tileSpan: {
    1: "(min-width: 1024px) 380px, (min-width: 640px) 50vw, 100vw",
    2: "(min-width: 1024px) 740px, 100vw",
    3: "(min-width: 1024px) 1120px, 100vw",
  } as Record<1 | 2 | 3, string>,
} as const;

/** Every photo variant is generated at this single ratio. */
export const PHOTO_RATIO = { width: 1024, height: 768 } as const;
