const data=await fetch("data/launch-manifest.json").then(r=>{if(!r.ok)throw new Error("Run npm run distribution:generate first.");return r.json()});
const records=data.records, $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const counts={approved:records.filter(r=>r.publish_status==="approved").length,scheduled:records.filter(r=>r.publish_status==="scheduled").length,published:records.filter(r=>r.publish_status==="published").length,awaiting:records.filter(r=>r.publish_status==="published"&&r.performance_status!=="complete").length};
$("#summary").innerHTML=[["Approved assets",new Set(records.map(r=>r.asset_id)).size],["Scheduled",counts.scheduled],["Published",counts.published],["Awaiting performance",counts.awaiting],["Best performer","—"]].map(([l,v])=>`<div class="stat"><strong>${v}</strong><span>${l}</span></div>`).join("");
const thumb=r=>r.format==="short"?(r.cover_path||r.asset_path):r.asset_path;
$("#queue").innerHTML=`<div class="queue-head"><span>Date</span><span>Platform</span><span>Preview</span><span>Asset</span><span>Content job</span><span>Primary metric</span><span>Status</span></div>`+records.map(r=>`<article class="card" data-id="${r.distribution_id}"><time>${r.scheduled_date.slice(5)}</time><span class="platform">${esc(r.platform)}</span><img class="thumb" src="${esc(thumb(r))}" alt=""><div><strong>${esc(r.headline)}</strong><small><br>${esc(r.source_path)}</small></div><span>${esc(r.content_job)}</span><span>${esc(r.primary_metric)}</span><span class="status">${r.publish_status}</span></article>`).join("");
const days=[...new Set(records.map(r=>r.scheduled_date))]; $("#calendar").classList.add("calendar"); $("#calendar").innerHTML=days.map((d,i)=>`<article class="day"><small>DAY ${i+1} · ${d.slice(5)}</small><h3>${new Date(`${d}T12:00:00`).toLocaleDateString("en-US",{weekday:"short"})}</h3>${records.filter(r=>r.scheduled_date===d).map(r=>`<button class="pill" data-id="${r.distribution_id}" data-platform="${r.platform}"><strong>${esc(r.platform)}</strong><br>${esc(r.headline)}</button>`).join("")}</article>`).join("");
const groups=[...new Set(records.map(r=>r.content_job))]; $("#scorecard").innerHTML=`<p>No winners are declared until real data exists. Compare each job on its appropriate measures.</p><div class="score-grid">${groups.map(g=>{const rs=records.filter(r=>r.content_job===g);return `<div class="panel"><small>CONTENT JOB</small><h3>${esc(g)}</h3><p>${rs.length} packages</p><p><b>Primary:</b> ${esc([...new Set(rs.map(r=>r.primary_metric))].join(", "))}</p><p>Awaiting real performance data.</p></div>`}).join("")}</div>`;
const checklistLabels={correct_final_asset:"correct final asset",correct_platform_dimensions:"correct platform dimensions",source_truth_current:"source truth current",provenance_approved:"provenance approved",caption_reviewed:"caption reviewed",destination_verified:"destination verified",utm_verified:"UTM verified",cta_reviewed:"CTA reviewed",alt_text_present:"alt text present where applicable",cover_verified:"cover verified",platform_safe_crop:"platform-safe crop",no_quarantined_media:"no quarantined media"};
function field(label,value,copy=true){return `<div class="field"><label>${label}</label><div class="value">${esc(Array.isArray(value)?value.join(" "):value)}</div>${copy?`<button class="copy" data-copy="${esc(Array.isArray(value)?value.join(" "):value)}">Copy</button>`:""}</div>`}
function openDetail(id){const r=records.find(x=>x.distribution_id===id);if(!r)return;const media=r.format==="short"?`<video controls muted poster="${esc(r.cover_path||"")}"><source src="${esc(r.asset_path)}"></video>`:`<img src="${esc(r.asset_path)}" alt="${esc(r.alt_text)}">`;$("#detail-content").innerHTML=`<div class="detail-grid"><div class="preview">${media}</div><div class="detail-copy"><p class="eyebrow" style="color:#71354a">${esc(r.platform)} · ${esc(r.content_job)}</p><h2>${esc(r.headline)}</h2>${field("Title",r.platform_title)}${field("Caption",r.platform_caption)}${field("Hashtags",r.hashtags)}${field("Destination URL",r.destination_url)}${field("Acquisition hypothesis",r.hypothesis,false)}${field("Source page",r.source_path,false)}${field("Provenance",`${r.visual_treatment}; approved registry media; no quarantine path`,false)}<h3>Publish checklist</h3><div class="checklist">${Object.entries(r.checklist).map(([k,v])=>`<div class="check ${v?"ok":""}">${v?"✓":"□"} ${checklistLabels[k]}</div>`).join("")}</div></div></div>`;$("#detail").showModal()}
document.addEventListener("click",async e=>{const target=e.target.closest("[data-id]");if(target)openDetail(target.dataset.id);const copy=e.target.closest(".copy");if(copy){await navigator.clipboard.writeText(copy.dataset.copy);copy.textContent="Copied";setTimeout(()=>copy.textContent="Copy",900)}});$(".close").onclick=()=>$("#detail").close();
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));$(`#${b.dataset.view}`).classList.remove("hidden")});
