import {distributionManifestSchema, type DistributionRecord} from "./schema.ts";

const emptyPerformance = {impressions:null,views:null,three_second_views:null,average_watch_time:null,completion_rate:null,outbound_clicks:null,outbound_ctr:null,saves:null,shares:null,likes:null,comments:null,site_sessions:null,engaged_visits:null,newsletter_signups:null,internal_conversions:null,affiliate_clicks:null};
const approvedChecklist = {correct_final_asset:true,correct_platform_dimensions:true,source_truth_current:true,provenance_approved:true,caption_reviewed:true,destination_verified:true,utm_verified:true,cta_reviewed:true,alt_text_present:true,cover_verified:true,platform_safe_crop:true,no_quarantined_media:true};
const campaign = "duck-breast-launch";
const dateFor = (day:number) => {const d=new Date(Date.UTC(2026,7,23+day)); return d.toISOString().slice(0,10);};
const slug = (value:string) => value.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
export const withUtm = (canonical:string, source:string, content:string) => {
  const url = new URL(canonical); url.searchParams.set("utm_source", slug(source)); url.searchParams.set("utm_medium", "social");
  url.searchParams.set("utm_campaign", campaign); url.searchParams.set("utm_content", slug(content)); return url.toString();
};

type Base = Pick<DistributionRecord,"asset_id"|"source_path"|"canonical_url"|"content_job"|"headline"|"description"|"alt_text"|"cta"|"asset_path"|"visual_treatment">;
const pinAssets: Record<string, Base & {search:string}> = {
  temp:{asset_id:"DD-LEARN-duck-temp-PIN-20260823-v01",source_path:"/learn/duck-breast-temperature-doneness",canonical_url:"https://deliciousduck.com/learn/duck-breast-temperature-doneness",content_job:"reference",headline:"Duck Breast Temperature Guide",description:"Pull temperature, carryover and the official safety minimum—one clear reference.",alt_text:"Sliced duck breast with rendered skin and a clear temperature-guide headline.",cta:"Get the temperature guide",asset_path:"../output/pinterest/DD-LEARN-duck-temp-PIN-20260823-v01.png",visual_treatment:"photography",search:"duck breast temperature guide"},
  recipe:{asset_id:"DD-RECIPE-pan-seared-PIN-20260823-v01",source_path:"/recipes/pan-seared-duck-breast",canonical_url:"https://deliciousduck.com/recipes/pan-seared-duck-breast",content_job:"outcome",headline:"Pan-Seared Duck Breast",description:"A cold-pan recipe with exact timing, temperature context and a five-minute rest.",alt_text:"Pan-seared duck breast sliced with crisp skin.",cta:"Cook the recipe",asset_path:"../output/pinterest/DD-RECIPE-pan-seared-PIN-20260823-v01.png",visual_treatment:"photography",search:"pan seared duck breast"},
  probe:{asset_id:"DD-LEARN-where-to-probe-PIN-20260823-v01",source_path:"/learn/duck-breast-temperature-doneness",canonical_url:"https://deliciousduck.com/learn/duck-breast-temperature-doneness",content_job:"reference",headline:"Where to Probe a Duck Breast",description:"Enter from the side and aim for the centre of the thickest part—not the fat cap or pan.",alt_text:"Approved technical probe-placement reference showing side entry into the centre of a duck breast.",cta:"See the placement guide",asset_path:"../output/pinterest/DD-LEARN-where-to-probe-PIN-20260823-v01.png",visual_treatment:"technical-illustration",search:"where to probe duck breast"},
  beginner:{asset_id:"DD-RECIPE-beginner-breast-PIN-20260823-v01",source_path:"/recipes/pan-seared-duck-breast",canonical_url:"https://deliciousduck.com/recipes/pan-seared-duck-breast",content_job:"beginner confidence",headline:"First Duck Breast? Start Here",description:"One pan, one thermometer, and cues you can actually see.",alt_text:"Sliced duck breast with rendered skin and a beginner-focused headline.",cta:"Start with the recipe",asset_path:"../output/pinterest/DD-RECIPE-beginner-breast-PIN-20260823-v01.png",visual_treatment:"photography",search:"duck breast for beginners"},
  crisp:{asset_id:"DD-LEARN-crisp-failures-PIN-20260823-v01",source_path:"/learn/why-duck-skin-isnt-crispy",canonical_url:"https://deliciousduck.com/learn/why-duck-skin-isnt-crispy",content_job:"problem/solution",headline:"Why Duck Skin Won’t Get Crispy",description:"Match the symptom: wet skin, hot start, crowding, pooled fat or a bad rest.",alt_text:"Pan-seared duck breast with crisp skin and a troubleshooting headline.",cta:"Diagnose the failure",asset_path:"../output/pinterest/DD-LEARN-crisp-failures-PIN-20260823-v01.png",visual_treatment:"photography",search:"why duck skin is not crispy"},
  cold:{asset_id:"DD-COOK-cold-pan-PIN-20260823-v01",source_path:"/cook/how-to-cook-duck-breast",canonical_url:"https://deliciousduck.com/cook/how-to-cook-duck-breast",content_job:"technique",headline:"Start Duck Breast in a Cold Pan",description:"Give the fat time to render before the exterior burns.",alt_text:"Pan-seared duck breast with a cold-pan method headline.",cta:"Learn the cold-pan method",asset_path:"../output/pinterest/DD-COOK-cold-pan-PIN-20260823-v01.png",visual_treatment:"photography",search:"start duck breast in cold pan"},
  doneness:{asset_id:"DD-LEARN-doneness-cues-PIN-20260823-v01",source_path:"/learn/duck-breast-temperature-doneness",canonical_url:"https://deliciousduck.com/learn/duck-breast-temperature-doneness",content_job:"decision",headline:"Duck Doneness: What Temperature Actually Means",description:"Culinary texture targets and the 165°F safety minimum answer different questions.",alt_text:"Sliced duck breast with rendered skin and doneness guidance.",cta:"Compare every target",asset_path:"../output/pinterest/DD-LEARN-doneness-cues-PIN-20260823-v01.png",visual_treatment:"photography",search:"duck breast doneness temperature"},
  checklist:{asset_id:"DD-LEARN-crisp-checklist-PIN-20260823-v01",source_path:"/learn/why-duck-skin-isnt-crispy",canonical_url:"https://deliciousduck.com/learn/why-duck-skin-isnt-crispy",content_job:"reference",headline:"Crispy Duck Skin Checklist",description:"Dry. Score. Start cold. Pour off fat. Flip on colour. Rest skin-up.",alt_text:"Approved scoring-depth illustration with a concise crisp-skin checklist.",cta:"Keep the full checklist",asset_path:"../output/pinterest/DD-LEARN-crisp-checklist-PIN-20260823-v01.png",visual_treatment:"technical-illustration",search:"crispy duck skin checklist"},
  render:{asset_id:"DD-COOK-render-cold-PIN-20260823-v01",source_path:"/cook/how-to-cook-duck-breast",canonical_url:"https://deliciousduck.com/cook/how-to-cook-duck-breast",content_job:"technique",headline:"Cold-Pan Rendering Method",description:"Render gradually, pour off fat, then finish on colour and temperature.",alt_text:"Pan-seared duck breast with a cold-pan rendering method headline.",cta:"Follow the method",asset_path:"../output/pinterest/DD-COOK-render-cold-PIN-20260823-v01.png",visual_treatment:"photography",search:"cold pan duck breast method"},
};

const common = (base:Base, day:number, platform:DistributionRecord["platform"], format:DistributionRecord["format"], content:string): DistributionRecord => ({
  distribution_id:`DD-DIST-${platform.toUpperCase().replace(/[^A-Z]/g,"-")}-${String(day).padStart(2,"0")}-${slug(content).toUpperCase()}-v01`,...base,
  platform,format,cluster:"duck-breast",series:"Duck Breast Field Notes",platform_title:base.headline,platform_caption:`${base.description} ${base.cta}.`,hashtags:[],
  destination_url:withUtm(base.canonical_url,platform.startsWith("instagram")?"instagram":platform.replace("-shorts",""),content),
  utm_source:platform.startsWith("instagram")?"instagram":platform.replace("-shorts",""),utm_medium:"social",utm_campaign:campaign,utm_content:slug(content),
  hypothesis:"Useful, source-grounded packaging will earn qualified attention and a visit to the aligned guide.",primary_metric:"outbound_clicks",secondary_metric:"saves",
  cover_path:null,caption_path:null,publish_status:"approved",scheduled_date:dateFor(day),published_at:null,external_post_id:null,external_post_url:null,
  performance_status:"not-started",performance:{...emptyPerformance},checklist:{...approvedChecklist},notes:"Manual publish only; no external scheduling has occurred.",search_intent:null,slide_count:null,
});
const pin = (key:keyof typeof pinAssets, day:number, content:string) => ({...common(pinAssets[key],day,"pinterest","pin",content),platform_title:pinAssets[key].headline,search_intent:pinAssets[key].search,hypothesis:`${pinAssets[key].content_job} framing will earn qualified outbound clicks from people searching for ${pinAssets[key].search}.`});

const videoAssets = {
  cold:{asset_id:"DD-Start-It-Cold",source_path:"/cook/how-to-cook-duck-breast",canonical_url:"https://deliciousduck.com/cook/how-to-cook-duck-breast",content_job:"counterintuitive technique",headline:"Start It Cold",description:"Duck breast needs a quiet start so the fat can render before the skin burns.",alt_text:"Vertical editorial short explaining the cold-pan duck breast method.",cta:"Read the cold-pan method",asset_path:"../output/video/DD-Start-It-Cold.mp4",visual_treatment:"animated approved photography"},
  probe:{asset_id:"DD-Where-To-Probe",source_path:"/learn/duck-breast-temperature-doneness",canonical_url:"https://deliciousduck.com/learn/duck-breast-temperature-doneness",content_job:"technical reference",headline:"Where To Probe",description:"Where you probe changes the number. Enter from the side and target the centre.",alt_text:"Vertical technical short showing correct thermometer placement in duck breast.",cta:"Use the temperature reference",asset_path:"../output/video/DD-Where-To-Probe.mp4",visual_treatment:"approved technical illustration"},
  crisp:{asset_id:"DD-Crisp-Skin-Finally",source_path:"/learn/why-duck-skin-isnt-crispy",canonical_url:"https://deliciousduck.com/learn/why-duck-skin-isnt-crispy",content_job:"problem/solution",headline:"Crisp Skin, Finally",description:"Five crisp-skin failure signals you can actually fix.",alt_text:"Vertical editorial short diagnosing five causes of soft duck skin.",cta:"Diagnose the crisp-skin failure",asset_path:"../output/video/DD-Crisp-Skin-Finally.mp4",visual_treatment:"animated approved photography"},
} satisfies Record<string,Base>;
const video = (key:keyof typeof videoAssets, day:number, platform:"tiktok"|"instagram-reels"|"youtube-shorts") => {
  const b=videoAssets[key], content=`${slug(b.headline)}-v01`, r=common(b,day,platform,"short",content);
  const hook=key==="cold"?"Your pan is probably too hot.":key==="probe"?"Where you probe changes the number.":"Crisp skin, finally.";
  const title=platform==="youtube-shorts"?`${b.headline} | Duck Breast Technique`:hook;
  const tags=key==="probe"?["#DuckBreast","#CookingTemperature","#FoodSafety"]:["#DuckBreast","#CookingTips","#CrispySkin"];
  return {...r,platform_title:title,platform_caption:platform==="instagram-reels"?`${hook}\n\n${b.description}\n\n${b.cta}.`: `${hook} ${b.description} ${b.cta}.`,hashtags:tags,
    cover_path:platform==="instagram-reels"?`../output/video/covers/DD-COOK-${slug(b.headline)}-COVER-20260823-v01.png`:null,
    primary_metric:platform==="instagram-reels"?"average_watch_time":"completion_rate",secondary_metric:platform==="instagram-reels"?"shares_and_saves":"average_watch_time",
    hypothesis:`The direct ${hook.toLowerCase()} opening will hold relevant viewers through the source-grounded resolution.`};
};
const carousel = (kind:"crisp"|"temp",day:number) => {
 const crisp=kind==="crisp", b:Base={asset_id:crisp?"DD-LEARN-crisp-skin-CAR-20260823-v01":"DD-LEARN-duck-temp-CAR-20260823-v01",source_path:crisp?"/learn/why-duck-skin-isnt-crispy":"/learn/duck-breast-temperature-doneness",canonical_url:crisp?"https://deliciousduck.com/learn/why-duck-skin-isnt-crispy":"https://deliciousduck.com/learn/duck-breast-temperature-doneness",content_job:crisp?"problem/solution":"reference",headline:crisp?"Why Your Duck Skin Won’t Crisp":"Duck Doneness Is Not One Number",description:crisp?"Five crisp-skin failures, the cue for each, and the checklist worth saving.":"Pull temperature, final temperature, placement and the official safety minimum—kept distinct.",alt_text:crisp?"Seven-slide carousel diagnosing crisp-skin failures.":"Seven-slide carousel explaining duck temperature and doneness context.",cta:crisp?"Save this, then read the troubleshooting guide":"Save the reference and open the full safety context",asset_path:crisp?"../output/instagram/carousels/DD-LEARN-crisp-skin-CAR-20260823-v01-s1.png":"../output/instagram/carousels/DD-LEARN-duck-temp-CAR-20260823-v01-s1.png",visual_treatment:crisp?"mixed approved photography":"mixed approved photography and technical illustration"};
 return {...common(b,day,"instagram-carousel","carousel",`${crisp?"crisp-skin":"doneness"}-carousel-v01`),platform_caption:`${b.headline}. ${b.description} ${b.cta}.`,primary_metric:"saves",secondary_metric:"shares",slide_count:7,hypothesis:"A saveable, seven-step utility sequence will earn saves and shares from cooks who need the guidance at the stove."};
};

export const distributionManifest = distributionManifestSchema.parse({version:1,generated_at:"2026-08-23T22:00:00.000Z",campaign,timezone:"America/New_York",records:[
 pin("temp",1,"temperature-guide-v01"),...(["tiktok","instagram-reels","youtube-shorts"] as const).map(p=>video("cold",2,p)),pin("recipe",3,"pan-seared-duck-breast-v01"),carousel("crisp",4),pin("probe",5,"where-to-probe-v01"),...(["tiktok","instagram-reels","youtube-shorts"] as const).map(p=>video("probe",6,p)),pin("beginner",7,"first-duck-breast-v01"),pin("crisp",8,"crisp-skin-troubleshooting-v01"),...(["tiktok","instagram-reels","youtube-shorts"] as const).map(p=>video("crisp",9,p)),carousel("temp",10),pin("cold",11,"start-it-cold-v01"),pin("doneness",12,"doneness-meaning-v01"),pin("checklist",13,"crispy-skin-checklist-v01"),pin("render",14,"cold-pan-rendering-v01")
]});
