/**
 * Generates the external analytics bootstrap asset served at /dd-boot.js.
 *
 * The QA-exclusion flag and the GA4 gate have to run before any tag is
 * requested, but they do not need to be *inline* to do that: a blocking
 * same-origin script in <head> runs at exactly the same point in the parse and
 * is cached across pages, instead of re-shipping ~2.4 KB of JavaScript inside
 * every server-rendered document.
 *
 * Run with:  bun scripts/gen-boot-script.ts
 * Drift is caught by src/lib/__tests__/boot-script-asset.test.ts.
 */
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { GA_MEASUREMENT_ID } from "../src/lib/analytics";
import { gtagBootstrapScript } from "../src/lib/analytics-gate";
import { minifyInlineScript } from "../src/lib/inline-script";
import { qaExclusionBootstrapScript } from "../src/lib/qa-exclusion";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));

/** The exact bytes that must be served at /dd-boot.js. */
export function bootScriptSource(): string {
  return [
    minifyInlineScript(qaExclusionBootstrapScript()),
    minifyInlineScript(gtagBootstrapScript(GA_MEASUREMENT_ID)),
  ].join("\n");
}

/** Short content hash used as the cache-busting query for the asset URL. */
export function bootScriptVersion(source = bootScriptSource()): string {
  return createHash("sha256").update(source).digest("hex").slice(0, 8);
}

export function bootScriptModule(version = bootScriptVersion()): string {
  return `/**
 * GENERATED by scripts/gen-boot-script.ts — do not edit by hand.
 * Cache-busting version for the /dd-boot.js analytics bootstrap asset.
 */
export const BOOT_SCRIPT_SRC = "/dd-boot.js?v=${version}";
`;
}

if (import.meta.main) {
  const source = bootScriptSource();
  writeFileSync(resolve(SCRIPT_DIR, "../public/dd-boot.js"), `${source}\n`, "utf8");
  writeFileSync(
    resolve(SCRIPT_DIR, "../src/lib/boot-script.ts"),
    bootScriptModule(bootScriptVersion(source)),
    "utf8",
  );
  console.log(`wrote public/dd-boot.js (${source.length} bytes) v=${bootScriptVersion(source)}`);
}
