import React from "react";
import {AbsoluteFill, Img, staticFile} from "remotion";
import {loadFont as loadNewsreader} from "@remotion/google-fonts/Newsreader";
import {loadFont as loadManrope} from "@remotion/google-fonts/Manrope";
import type {StillSpec} from "../content/asset-specs";
import {brand} from "../brand/tokens";

const newsreader = loadNewsreader("normal", {weights: ["500", "600"], subsets: ["latin"]}).fontFamily;
const manrope = loadManrope("normal", {weights: ["400", "500", "600", "700"], subsets: ["latin"]}).fontFamily;
const palette = (tone: StillSpec["tone"]) => tone === "cranberry" ? {bg: brand.color.cranberry, fg: brand.color.ivory, accent: brand.color.gold} : tone === "ivory" ? {bg: brand.color.ivory, fg: brand.color.forestInk, accent: brand.color.cranberry} : {bg: brand.color.forestInk, fg: brand.color.ivory, accent: brand.color.gold};

const BrandMark: React.FC<{light?: boolean; size: number}> = ({light, size}) => <div style={{display: "flex", alignItems: "center", gap: size * .24}}><div style={{width: size, height: size, borderRadius: "50%", background: light ? brand.color.ivory : brand.color.forestInk, display: "grid", placeItems: "center", overflow: "hidden"}}><Img src={staticFile(brand.mark)} style={{width: "78%", height: "78%", objectFit: "contain"}}/></div><div style={{fontFamily: newsreader, fontSize: size * .52, fontWeight: 600, letterSpacing: "-.025em"}}>DeliciousDuck</div></div>;

const TechniqueOverlay: React.FC<{slot: StillSpec["mediaSlot"]; scale: number}> = ({slot, scale}) => {
  const label = slot === "scoringDepthAnatomy" ? "SKIN + FAT · NOT MEAT" : slot === "technicalProbePlacement" ? "→ THICKEST-PART CENTRE" : null;
  if (!label) return null;
  return <div style={{position:"absolute",right:32*scale,bottom:32*scale,padding:`${11*scale}px ${16*scale}px`,borderRadius:999,background:"rgba(16,37,27,.9)",color:brand.color.ivory,fontFamily:manrope,fontWeight:700,fontSize:13*scale,letterSpacing:".12em",boxShadow:"0 8px 28px rgba(0,0,0,.18)"}}><span style={{color:brand.color.gold,marginRight:8*scale}}>●</span>{label}</div>;
};

const ReferenceRows: React.FC<{spec: StillSpec; scale: number}> = ({spec, scale}) => <div style={{display: "grid", gap: 12 * scale, marginTop: 20 * scale}}>{spec.rows?.map((row, index) => <div key={row.label} style={{display: "grid", gridTemplateColumns: "1fr 1.05fr 1.55fr", alignItems: "center", gap: 16 * scale, padding: `${15 * scale}px ${20 * scale}px`, background: index === 2 ? brand.color.cranberry : "rgba(255,253,248,.84)", color: index === 2 ? brand.color.ivory : brand.color.forestInk, borderRadius: 14 * scale}}><div style={{fontFamily: manrope, fontWeight: 700, fontSize: 19 * scale, textTransform: "uppercase", letterSpacing: ".06em"}}>{row.label}</div><div style={{fontFamily: newsreader, fontWeight: 600, fontSize: 30 * scale}}>{row.value}</div><div style={{fontFamily: manrope, fontSize: 16 * scale, lineHeight: 1.3}}>{row.note}</div></div>)}</div>;

const ArtStage: React.FC<{spec: StillSpec; variant: number; scale: number}> = ({spec, variant, scale}) => {
  const vertical = spec.height / spec.width > 1.25;
  const base = vertical ? (variant === 1 ? {left: "42%", right: 28 * scale, top: 570 * scale, bottom: 125 * scale} : variant === 2 ? {left: 70 * scale, right: 70 * scale, top: 570 * scale, bottom: 265 * scale} : {left: "34%", right: 24 * scale, top: 570 * scale, bottom: 110 * scale}) : {left: "46%", right: 20 * scale, top: 125 * scale, bottom: 90 * scale};
  return <div style={{position: "absolute", ...base, overflow: "hidden", borderRadius: 42 * scale, background: "rgba(255,253,248,.96)", display: "grid", placeItems: "center"}}>{spec.image ? <Img src={staticFile(spec.image)} style={{width: "100%", height: "100%", objectFit: spec.mediaSlot === "technicalProbePlacement" || spec.mediaSlot === "scoringDepthAnatomy" ? "contain" : "cover", objectPosition: "center", transform:spec.mediaSlot === "scoringDepthAnatomy"?"scale(1.38)":undefined}}/> : null}<TechniqueOverlay slot={spec.mediaSlot} scale={scale}/></div>;
};

export const EditorialStill: React.FC<{spec: StillSpec}> = ({spec}) => {
  const p = palette(spec.tone); const scale = spec.width / 1080; const isPhoto = spec.preferredTreatment === "photography"; const isRef = spec.kind === "reference"; const slideIndex = spec.slide ? Number(spec.slide.split("/")[0]?.trim() ?? 1) - 1 : 0; const variant = spec.composition ?? (spec.kind === "carousel" ? slideIndex % 3 : spec.kind === "pin" ? (spec.id.length + spec.headline.length) % 3 : 0); const vertical = spec.height / spec.width > 1.25;
  if (spec.clean) return <AbsoluteFill style={{backgroundColor: brand.color.forestInk}}>{spec.image && <Img src={staticFile(spec.image)} style={{position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: isPhoto ? "cover" : "contain", background: brand.color.ivory, filter: isPhoto ? "brightness(1.08) saturate(1.04)" : undefined}}/>}{isPhoto && <div style={{position: "absolute", inset: 0, background: "linear-gradient(180deg,transparent 55%,rgba(16,37,27,.66))"}}/>}<div style={{position: "absolute", left: 82 * scale, bottom: 170 * scale, color: brand.color.ivory}}><BrandMark light size={58 * scale}/></div></AbsoluteFill>;
  return <AbsoluteFill style={{backgroundColor: p.bg, color: p.fg, fontFamily: manrope, overflow: "hidden"}}>
    {isPhoto && spec.image ? <><Img src={staticFile(spec.image)} style={{position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover", objectPosition: spec.imagePosition ?? (variant === 1 ? "62% center" : variant === 2 ? "center 35%" : "center"), filter: "brightness(1.16) saturate(1.03) contrast(.97)"}}/><div style={{position: "absolute", inset: 0, background: variant === 1 ? "linear-gradient(90deg,rgba(16,37,27,.82) 0 48%,rgba(16,37,27,.08) 82%)" : variant === 2 ? "linear-gradient(180deg,rgba(16,37,27,.76) 0 36%,rgba(16,37,27,.08) 72%)" : "linear-gradient(180deg,rgba(16,37,27,.66) 0 32%,rgba(16,37,27,.08) 58%,rgba(16,37,27,.76) 92%)"}}/><TechniqueOverlay slot={spec.mediaSlot} scale={scale}/></> : <ArtStage spec={spec} variant={variant} scale={scale}/>} 
    {!isPhoto && <><div style={{position: "absolute", width: 540 * scale, height: 540 * scale, border: `${2 * scale}px solid ${p.accent}`, borderRadius: "50%", opacity: .13, right: -250 * scale, top: -190 * scale}}/><div style={{position: "absolute", left: 0, top: 0, width: 12 * scale, height: "100%", background: p.accent}}/></>}
    <div style={{position: "absolute", left: 76 * scale, right: 76 * scale, top: (isRef ? 52 : 80) * scale, bottom: (spec.kind === "story" ? 230 : 76) * scale, display: "flex", flexDirection: "column"}}>
      <div style={{display: "flex", justifyContent: "space-between", gap: 26 * scale, alignItems: "center"}}><div style={{fontSize: 18 * scale, fontWeight: 700, letterSpacing: ".19em", textTransform: "uppercase", color: isPhoto ? brand.color.gold : spec.tone === "ivory" ? brand.color.authorityGreen : p.accent}}>{spec.eyebrow}</div>{spec.slide && <div style={{fontSize: 18 * scale, fontWeight: 700, letterSpacing: ".14em"}}>{spec.slide}</div>}</div>
      <div style={{marginTop: (isRef ? 20 : 34) * scale, maxWidth: isRef ? "72%" : !isPhoto && vertical ? "88%" : variant === 1 ? "47%" : vertical ? "82%" : "72%"}}><h1 style={{fontFamily: newsreader, fontWeight: 600, fontSize: (isRef ? 54 : vertical ? 86 : 76) * scale, lineHeight: .94, letterSpacing: "-.038em", margin: 0}}>{spec.headline}</h1><div style={{fontSize: (isRef ? 22 : 28) * scale, lineHeight: 1.3, marginTop: 22 * scale, maxWidth: 780 * scale, color: isPhoto ? brand.color.ivory : spec.tone === "ivory" ? "#30473C" : p.fg}}>{spec.subhead}</div></div>
      {isRef && <div style={{width: spec.height / spec.width < .8 ? "72%" : "100%"}}><ReferenceRows spec={spec} scale={scale}/></div>}
      <div style={{marginTop: "auto", display: "flex", justifyContent: "space-between", alignItems: "flex-end", gap: 30 * scale}}><BrandMark light={isPhoto || spec.tone !== "ivory"} size={48 * scale}/>{spec.cta && <div style={{fontSize: 19 * scale, fontWeight: 700, letterSpacing: ".07em", textTransform: "uppercase", background: p.accent, color: spec.tone === "cranberry" ? brand.color.forestInk : brand.color.ivory, padding: `${14 * scale}px ${22 * scale}px`, borderRadius: 999, maxWidth: 430 * scale, textAlign: "right"}}>{spec.cta}</div>}</div>
    </div>
    {spec.kind === "story" && <div style={{position: "absolute", left: 82 * scale, right: 82 * scale, bottom: 74 * scale, height: 116 * scale, border: `${2 * scale}px dashed rgba(243,231,211,.52)`, borderRadius: 22 * scale, display: "grid", placeItems: "center", fontSize: 16 * scale, letterSpacing: ".13em", textTransform: "uppercase"}}>Reserved for native interaction</div>}
  </AbsoluteFill>;
};
